In [1]:
!pip install datascience

In [2]:

import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [3]:
# question 1

In [4]:
import math

In [5]:
weird_numbers = [-2, math.floor(17.6), 3, math.pow(5,5.3)]
weird_numbers

[-2, 17, 3, 5064.551864664882]

In [6]:
# question 2

In [7]:
book_title_words = ["Eats", "Shoot", "and Leaves"]
book_title_words

['Eats', 'Shoot', 'and Leaves']

In [8]:
# question 3

In [9]:
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoot, and Leaves
without_commas: Eats Shoot and Leaves


In [10]:
# part 2 question 1

In [11]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers.item(2)
third_element

-6

In [12]:
# question 2

In [13]:
blank_a = "third"
blank_b = "fourth"
blank_c = 0
blank_d = 3
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

In [14]:
# question 3

In [15]:
index_of_last_element = 141

In [16]:
# question 4

In [17]:
president_birth_years = Table.read_table("./csv/president_births.csv").column('Birth Year')

most_recent_birth_year = president_birth_years.item(len(president_birth_years)-1)
most_recent_birth_year

1917

In [18]:
# question 5

In [19]:
min_of_birth_years = min(president_birth_years.item(0), president_birth_years.item(15), president_birth_years.item(len(president_birth_years)-1))
min_of_birth_years

1732

In [20]:
# part 3 question 1

In [21]:
first_product = 42*157
second_product = -4224*157
third_product = 424224242*157
fourth_product = 250*157
print("First Product:", first_product)
print("Second Product:", second_product)
print("Third Product:", third_product)
print("Fourth Product:", fourth_product)

First Product: 6594
Second Product: -663168
Third Product: 66603205994
Fourth Product: 39250


In [22]:
# question 2

In [23]:
numbers = make_array(42,-4224, 424224242, 250)
products = numbers*157
products

array([       6594,     -663168, 66603205994,       39250])

In [24]:
correct_products = numbers*1577
correct_products

array([       66234,     -6661248, 669001629634,       394250])

In [25]:

max_temperatures = Table.read_table("./csv/temperatures.csv").column("Daily Max Temperature")

max_temperatures_celsius = (max_temperatures-32)*5/9
celsius_temps_rounded = np.round(max_temperatures_celsius)
celsius_temps_rounded

array([ -4.,  31.,  32., ...,  17.,  23.,  16.])

In [26]:
min_temperatures = Table.read_table("./csv/temperatures.csv").column("Daily Min Temperature")
min_temperatures_celsius = (min_temperatures-32)*5/9

celsius_temperature_ranges = max_temperatures_celsius - min_temperatures_celsius
celsius_temperature_ranges

array([  6.66666667,  10.        ,  12.22222222, ...,  17.22222222,
        11.66666667,  11.11111111])

In [27]:
# part 4 question 1

In [28]:
waiting_times = Table.read_table('./csv/old_faithful.csv').column('waiting')

shortest = min(waiting_times)
longest = max(waiting_times)
average = np.average(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235 minutes on average.


In [29]:
# question 2

In [30]:

# np.diff() calculates the difference between subsequent values  
# in a NumPy array.
differences = np.diff(waiting_times)
biggest_decrease = max(differences)
biggest_decrease

47

In [31]:
# question 3

In [32]:
# The following two lines load in our faithful_with_eruption_nums table
faithful = Table.read_table('./csv/old_faithful.csv').drop("eruptions")
faithful_with_eruption_nums = faithful.with_column("eruption number", np.arange(faithful.num_rows) + 1).select(1, 0)

first_nine_waiting_times = faithful_with_eruption_nums.column("waiting")[:10]
total_waiting_time_until_tenth = sum(first_nine_waiting_times)
total_waiting_time_until_tenth

718

In [33]:
# question 4

In [34]:
differences = np.diff(waiting_times)

average_error = np.average(np.abs(differences))
average_error

20.520295202952031

In [35]:
# part 5 question 1

In [36]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns([
        ("fruit name", ["apples","oranges","pineapples"]),
        ("amount", [4,3,3])
])
fruits

fruit name | amount
apples     | 4
oranges    | 3
pineapples | 3

In [37]:
# question 2

In [38]:
inventory = Table.read_table("./csv/inventory.csv")
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [39]:
# question 3

In [40]:
all_different = False
all_different

False

In [41]:
# question 4

In [42]:
sales = Table.read_table("./csv/sales.csv")
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

In [43]:
# question 5

In [44]:
total_fruits_sold = sum(sales.column("count sold"))
total_fruits_sold

638

In [48]:
total_revenue = sum(sales.column("count sold")*sales.column("price per fruit ($)"))
total_revenue

106.84999999999999

In [49]:
remaining_inventory = inventory.with_column("count", inventory.column("count") -sales.column("count sold"))
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23